app.environment: production

server:
  port: 8761
  servlet.context-path: /discovery

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - health
    endpoint:
      health:
        show-details: when_authorized
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  environment: ${app.environment}
  datacenter: DIGDIR-EFM
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}${server.servlet.context-path}/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: git@ssh.dev.azure.com:v3/dificloud/eformidling/move-config
          search-paths: config
          force-pull: true
          basedir: /tmp/config_cache
        prefix: /config
        health:
          enabled: false
#  datasource:
#    url: jdbc:mysql://mysql:3306/eureka?useSSL=false&autoReconnect=true&serverTimezone=Europe/Oslo
#    username: eureka
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: "@project.name@"

info.app:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"