app.environment: production

server:
  port: 8762
  servlet.context-path: /discovery

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - health
    endpoint:
      health:
        show-details: when_authorized
  endpoint:
    health:
      probes:
        enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/eureka?useSSL=false&autoReconnect=true&serverTimezone=Europe/Oslo
    username: eureka
  application:
    name: "@project.name@"

info.app:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"